In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_2e027119b9e4408d9035f56d4aaaa5a6 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='jrJj_sOBiWoHjgfrJH5JC6ipasTw8gVKbQTNAUtnIREG',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

body = client_2e027119b9e4408d9035f56d4aaaa5a6.get_object(Bucket='ibmdataanalystcapstoneproject-donotdelete-pr-zguaxuyonixjnk',Key='Fraud.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

data = pd.read_csv(body)
data.head()


step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0  
3    C38997010         21182.0             0.0        1               0  
4  M1230701703             0.0             0.0        0               0

In [41]:
data.tail()

step      type      amount     nameOrig  oldbalanceOrg  \
6362615   743  CASH_OUT   339682.13   C786484425      339682.13   
6362616   743  TRANSFER  6311409.28  C1529008245     6311409.28   
6362617   743  CASH_OUT  6311409.28  C1162922333     6311409.28   
6362618   743  TRANSFER   850002.52  C1685995037      850002.52   
6362619   743  CASH_OUT   850002.52  C1280323807      850002.52   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
6362615             0.0   C776919290            0.00       339682.13        1   
6362616             0.0  C1881841831            0.00            0.00        1   
6362617             0.0  C1365125890        68488.84      6379898.11        1   
6362618             0.0  C2080388513            0.00            0.00        1   
6362619             0.0   C873221189      6510099.11      7360101.63        1   

         isFlaggedFraud  
6362615               0  
6362616               0  
6362617               0  
6362618               0  
6362619               0

In [42]:
data.shape

(6362620, 11)

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
 10  isFlaggedFraud  int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB


In [44]:
data.describe()

step        amount  oldbalanceOrg  newbalanceOrig  \
count  6.362620e+06  6.362620e+06   6.362620e+06    6.362620e+06   
mean   2.433972e+02  1.798619e+05   8.338831e+05    8.551137e+05   
std    1.423320e+02  6.038582e+05   2.888243e+06    2.924049e+06   
min    1.000000e+00  0.000000e+00   0.000000e+00    0.000000e+00   
25%    1.560000e+02  1.338957e+04   0.000000e+00    0.000000e+00   
50%    2.390000e+02  7.487194e+04   1.420800e+04    0.000000e+00   
75%    3.350000e+02  2.087215e+05   1.073152e+05    1.442584e+05   
max    7.430000e+02  9.244552e+07   5.958504e+07    4.958504e+07   

       oldbalanceDest  newbalanceDest       isFraud  isFlaggedFraud  
count    6.362620e+06    6.362620e+06  6.362620e+06    6.362620e+06  
mean     1.100702e+06    1.224996e+06  1.290820e-03    2.514687e-06  
std      3.399180e+06    3.674129e+06  3.590480e-02    1.585775e-03  
min      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00  
25%      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00  
50%      1.327057e+05    2.146614e+05  0.000000e+00    0.000000e+00  
75%      9.430367e+05    1.111909e+06  0.000000e+00    0.000000e+00  
max      3.560159e+08    3.561793e+08  1.000000e+00    1.000000e+00

In [45]:
data.isnull().sum()   #no null value

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [46]:
data.duplicated(keep = "first").sum() #no duplicate value

0

In [47]:
#checking if truly no duplicate value
data.drop_duplicates(ignore_index = True, inplace = True)

In [48]:
data.shape    #no duplicates

(6362620, 11)

In [49]:
data.drop(['nameOrig', 'nameDest'], axis=1)

step      type      amount  oldbalanceOrg  newbalanceOrig  \
0           1   PAYMENT     9839.64      170136.00       160296.36   
1           1   PAYMENT     1864.28       21249.00        19384.72   
2           1  TRANSFER      181.00         181.00            0.00   
3           1  CASH_OUT      181.00         181.00            0.00   
4           1   PAYMENT    11668.14       41554.00        29885.86   
...       ...       ...         ...            ...             ...   
6362615   743  CASH_OUT   339682.13      339682.13            0.00   
6362616   743  TRANSFER  6311409.28     6311409.28            0.00   
6362617   743  CASH_OUT  6311409.28     6311409.28            0.00   
6362618   743  TRANSFER   850002.52      850002.52            0.00   
6362619   743  CASH_OUT   850002.52      850002.52            0.00   

         oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0                  0.00            0.00        0               0  
1                  0.00            0.00        0               0  
2                  0.00            0.00        1               0  
3              21182.00            0.00        1               0  
4                  0.00            0.00        0               0  
...                 ...             ...      ...             ...  
6362615            0.00       339682.13        1               0  
6362616            0.00            0.00        1               0  
6362617        68488.84      6379898.11        1               0  
6362618            0.00            0.00        1               0  
6362619      6510099.11      7360101.63        1               0  

[6362620 rows x 9 columns]

In [50]:
data.shape 

(6362620, 11)

In [51]:
data['type'].value_counts()

CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: type, dtype: int64

In [52]:
data.replace({'type':{'CASH_OUT':0,'CASH_IN':1, 'PAYMENT':2, 'TRANSFER':3, 'DEBIT':4}}, inplace = True)  #inplace - replacement parameter

In [53]:
data['type'].value_counts()

0    2237500
2    2151495
1    1399284
3     532909
4      41432
Name: type, dtype: int64

In [54]:
data['isFlaggedFraud'].value_counts() 

0    6362604
1         16
Name: isFlaggedFraud, dtype: int64

In [55]:
data['isFraud'].value_counts() #highly unbalanced data 

0    6354407
1       8213
Name: isFraud, dtype: int64

In [56]:
legit = data[data.isFraud == 0]
fraud = data[data.isFraud == 1]

In [57]:
print(legit.shape)
print(fraud.shape)

(6354407, 11)
(8213, 11)


In [58]:
#compare values for normal and fraululent classes, compare value for mean
data.groupby('isFraud').mean()            #wide diff b/w mean this id imp thats how ML predicts 

step      type        amount  oldbalanceOrg  newbalanceOrig  \
isFraud                                                                      
0        243.235663  1.173113  1.781970e+05   8.328287e+05   855970.228109   
1        368.413856  1.496530  1.467967e+06   1.649668e+06   192392.631836   

         oldbalanceDest  newbalanceDest  isFlaggedFraud  
isFraud                                                  
0          1.101421e+06    1.224926e+06        0.000000  
1          5.442496e+05    1.279708e+06        0.001948

In [59]:
#Under Sampling
#build sample dataset from original dataset containing similar distributuion of legit and fraudulent transactoion
#no of fraudulent transaction ---> 8213
#goal is to make eqaul distribution so we will take 492 data from legit data to sample data

legit_sample = legit.sample(n = 8213) #it will take 492 data point randomly from legit, good way to take data into sample

In [60]:
concateneted_data = pd.concat([legit_sample, fraud], axis = 0)  # axis = 0 adding row wise concatenation. 
                                                                # axis = 1 add column wise dont want that

In [61]:
final_data = concateneted_data.drop(columns = ['nameOrig', 'nameDest'])

In [62]:
final_data.shape

(16426, 9)

In [63]:
final_data['isFraud'].value_counts()  #equal sample distribution 

0    8213
1    8213
Name: isFraud, dtype: int64

In [64]:
final_data.groupby('isFraud').mean()  #imp to check whether sample is good or not, the nature of dataset has not 
#changed, and diff is still there as earlier so now we can put this sample to train adnd Ml will give good result 

step      type        amount  oldbalanceOrg  newbalanceOrig  \
isFraud                                                                      
0        243.522343  1.159503  1.781991e+05   8.276582e+05   851285.909193   
1        368.413856  1.496530  1.467967e+06   1.649668e+06   192392.631836   

         oldbalanceDest  newbalanceDest  isFlaggedFraud  
isFraud                                                  
0          1.120399e+06    1.235999e+06        0.000000  
1          5.442496e+05    1.279708e+06        0.001948

In [65]:
X = final_data.iloc[:, 1:-2].values   #feature matrix
y = final_data.iloc[:, -2].values    #output

In [66]:
print(X)

[[1.00000000e+00 1.03428680e+05 5.79874210e+06 5.90217079e+06
  1.33575394e+06 1.23232526e+06]
 [0.00000000e+00 1.66249220e+05 4.16832000e+05 2.50582780e+05
  6.87287070e+05 8.53536290e+05]
 [0.00000000e+00 1.51916220e+05 0.00000000e+00 0.00000000e+00
  3.93781405e+06 4.08973027e+06]
 ...
 [0.00000000e+00 6.31140928e+06 6.31140928e+06 0.00000000e+00
  6.84888400e+04 6.37989811e+06]
 [3.00000000e+00 8.50002520e+05 8.50002520e+05 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.50002520e+05 8.50002520e+05 0.00000000e+00
  6.51009911e+06 7.36010163e+06]]


In [67]:
print(y)

[0 0 0 ... 1 1 1]


In [68]:
from sklearn.model_selection import train_test_split

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify = y, random_state = 2)  

In [70]:
print(X.shape, X_train.shape, X_test.shape) 

(16426, 6) (11498, 6) (4928, 6)


In [33]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [34]:
#accuracy score
#accuracy on training data
from sklearn.metrics import accuracy_score     
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, y_train) #X_train_prediction = h(x), y_train = y, 
                                                                     # accuracy = h(x) - y

In [35]:
print('accuracy on training data: ', training_data_accuracy)
#generally when prediction are more than 75% then predictions are good here in our case its 94% so our 
#predicted accuracy is very good

accuracy on training data:  0.8277091668116194


In [36]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 0]
 [1 0]
 ...
 [0 0]
 [1 1]
 [1 0]]


In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score,roc_auc_score,f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
acc=accuracy_score(y_test, y_pred)
pre=precision_score(y_test, y_pred)
rec=recall_score(y_test, y_pred)
print('precision score is: ', pre)
print('recall_score: ', rec)
print('accuracy',acc)
#y_pred = h(x), y_test = y, accuracy = h(x) - y

[[1648  816]
 [  73 2391]]
precision score is:  0.7455565949485501
recall_score:  0.9703733766233766
accuracy 0.8196022727272727


In [38]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000],
'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
'kernel': ['rbf']}

grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)

# print best parameter after tuning
# fitting the model for grid search
grid.fit(X_train, y_train)

# we can add class_weight='balanced' to add panalize mistake
svc_model = SVC(C=grid['C'],gamma=grid['gamma'],kernel=grid['kernel'],class_weight='balanced', probability=True)

svc_model.fit(X_train, y_train)

svc_predict = svc_model.predict(X_test)# check performance
print('ROCAUC score:',roc_auc_score(y_test, svc_predict))
print('Accuracy score:',accuracy_score(y_test, svc_predict))
print('F1 score:',f1_score(y_test, svc_predict))

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.504 total time=   4.4s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.502 total time=   4.5s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.502 total time=   4.4s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.505 total time=   4.4s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.503 total time=   4.4s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.504 total time=   4.4s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.502 total time=   4.4s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.502 total time=   4.4s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.505 total time=   4.5s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.503 total time=   4.4s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.504 total time=   4.5s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

[CV 2/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.504 total time=   9.1s
[CV 3/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.505 total time=   9.3s
[CV 4/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.507 total time=   9.0s
[CV 5/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.505 total time=   9.9s
[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.517 total time=   4.4s
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.517 total time=   5.0s
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.508 total time=   6.5s
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.512 total time=   5.1s
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.510 total time=   7.1s
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.530 total time=   9.4s
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.530 total time=   9.2s
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.532 total time=   9.3s
[CV 4/5] END ....C=1000, gam

TypeError: 'GridSearchCV' object is not subscriptable

In [ ]:
pre=precision_score(y_test, y_pred)
rec=recall_score(y_test, y_pred)
print('precision score is: ', pre)
print('recall_score: ', rec)

In [40]:
grid

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [44]:
gr=grid.best_params_

In [45]:
svc_model = SVC(C=gr['C'],gamma=gr['gamma'],kernel=gr['kernel'],class_weight='balanced', probability=True)

svc_model.fit(X_train, y_train)


SVC(C=10, class_weight='balanced', gamma=0.0001, probability=True)

In [46]:
svc_predict = svc_model.predict(X_test)# check performance
print('ROCAUC score:',roc_auc_score(y_test, svc_predict))
print('Accuracy score:',accuracy_score(y_test, svc_predict))
print('F1 score:',f1_score(y_test, svc_predict))

ROCAUC score: 0.6233766233766234
Accuracy score: 0.6233766233766234
F1 score: 0.3966189856957087


In [47]:
pre=precision_score(y_test, y_pred)
rec=recall_score(y_test, y_pred)
print('precision score is: ', pre)
print('recall_score: ', rec)

precision score is:  0.7455565949485501
recall_score:  0.9703733766233766


In [48]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[1648,  816],
       [  73, 2391]])

In [51]:
pd.DataFrame(y_test).value_counts()

0    2464
1    2464
dtype: int64

In [71]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [73]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score,roc_auc_score,f1_score
tree_predict = clf.predict(X_test)# check performance
print('ROCAUC score:',roc_auc_score(y_test, tree_predict))
print('Accuracy score:',accuracy_score(y_test, tree_predict))
print('F1 score:',f1_score(y_test, tree_predict))

ROCAUC score: 0.9906655844155843
Accuracy score: 0.9906655844155844
F1 score: 0.9906731549067316


In [75]:
y_pred = clf.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [0 0]]


In [76]:
pre=precision_score(y_test, y_pred)
rec=recall_score(y_test, y_pred)
print('precision score is: ', pre)
print('recall_score: ', rec)

precision score is:  0.9898703403565641
recall_score:  0.9914772727272727


In [77]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[2439,   25],
       [  21, 2443]])